### ISSUE TITLE
Add an option for onProgress to be called every N secods

### ISSUE THREAD

**Issue by DanAvni** [DNA-Evolutions/Java-TourOptimizer-Examples#1]
Currently the bigger the generation count is for the GA phase the longer it will take for onProgress to be called. furthermore, for very large values it could be many minutes between onProgress calls. Please add an option to have onProgress called every N seconds so I can provide the user with progress on a more rapid basis

**Comment by jrichter-svmx** [comment]
I see your point!

However, bounding the onProgress to a timer can be problematic. The onProgress method is called when a particular portion of the optimization is done. If we try to do this in a request manner (what adding a timer would implicitly mean), it could lead to back-pressure.

Alternatively, we can try to make these "certain portions," after which onPorgress is called, adjustable. Usually, these portions are pretty big. So adjusting them will lead approximately to your desired effect.

**Comment by DanAvni** [comment]
I do not think a timer needs to be added. it's enough to have a variable holding the next UTC time to throw an event and every chunk of work check if an event is needed or not. now the chunk of work needs to be much smaller than 1% of work which for 100000 generations is 1000 generations (and with 1000 nodes this might take a few minutes)

**Comment by jrichter-svmx** [comment]
The lower limit for throwing a progress report is precisely one generation. So in your example, you can get the onProgress 1000 times faster (after each generation). Let's assume in veeeery big problem sets it takes 10 minutes. Therefore you can theoretically speed it up to throw a result every 0.6 seconds (10min/1000).

**Comment by DanAvni** [comment]
Should work as well. Worst case I can measure time on my side of code assuming a onProgress callback is fired every 1 generation

**Comment by jrichter-svmx** [comment]
I think we should do both :-)

1) Letting you set a default desired value for the percentage. E.g. "give a progress after 0.1% or 0.02% etc."

2) Like request result, we add "request progress". This way you can avoid that the Optimizer is sending you too many reports. On your site, you can add a timer for performing the progress-requests.

**Comment by jrichter-svmx** [comment]
We added the desired feature. It will be available as part of the new build :-). I will close the issue once the new build is published.

**Comment by jrichter-svmx** [comment]
@DanAvni please check:

[Progress Frequency and request example](https://github.com/DNA-Evolutions/Java-TourOptimizer-Examples/tree/master/src/main/java/com/dna/jopt/touroptimizer/java/examples/advanced/progressfrequency
)

with latest released version 7.4.5-rc1
