### ISSUE TITLE
Allow SA & GA phases to run in an endless loop

### ISSUE THREAD

**Issue by DanAvni** [DNA-Evolutions/Java-TourOptimizer-Examples#2]
I want each phase to run as long as there is progress (with onProgress being fired every N seconds - see other issue I have opened on this). That way I can monitor its progress and once my code decides the phase is converged it will tell the engine to end the phase

**Comment by jrichter-svmx** [comment]
Hey,

this can be already achieved. I added an example :-)

[Check the example](https://github.com/DNA-Evolutions/Java-TourOptimizer-Examples/tree/master/src/main/java/com/dna/jopt/touroptimizer/java/examples/advanced/looprun)

Stay safe!

Best,
Jens
