### ISSUE TITLE
Please add to the onProgress event the raw data

### ISSUE THREAD

**Issue by DanAvni** [DNA-Evolutions/Java-TourOptimizer-Examples#3]
In the onProgress event, I can ask for the progress string. Please add methods to retrieve the raw data that makes up the progress string so I can use the raw information for my own logging format

**Comment by jrichter-svmx** [comment]
Hi Dani,

please check example:
https://github.com/DNA-Evolutions/Java-TourOptimizer-Examples/blob/master/src/main/java/com/dna/jopt/touroptimizer/java/examples/basic/io_03/Export2KMLExample.java

line 191. Here, we override the onProgress to get the Progress object instead of using the
progress string. Alternatively, attaching to the observable is also
emitting the progress object.

Best,
Jens

**Comment by jrichter-svmx** [comment]
..also, please read https://public.javadoc.dna-evolutions.com/  and search
for interface IOptimizationProgress and IOptimizationOutcome (its super interface)

Please let me know, if this solves your issue :-)

**Comment by DanAvni** [comment]
Hi Jens

I am already using the override of the onProgress using the interface but the interface only allows me to read the progress, the stage as an integer, and the progress string

I am interested in reading the values that make the string
PC 98.9, RE 1, AL GeneticEvolution, JC 20625.366085125752, RC 31, EC 745, TC 776, TT[h] 266, TU[%] 46, TD[km] 7251.786

so basically I need a property for reading
PC - exists
RE
AL string
JC - exists
RC
EC
TC
TT
TU
TD

That way I can log the data using my own format and not have to log JOPT provided string as-is

**Comment by jrichter-svmx** [comment]
Hi Dani, 

I added the following example:

https://github.com/DNA-Evolutions/Java-TourOptimizer-Examples/blob/master/src/main/java/com/dna/jopt/touroptimizer/java/examples/advanced/readoutfullprogress/ReadOutFullProgressExample.java

Please let me know if it helps.

Best,
Jens

**Comment by jrichter-svmx** [comment]
..However, I agree that this should be a little bit simpler...

**Comment by DanAvni** [comment]
Hi Jens

Thanks! I think the only missing thing is the temperature for the SA part but it is not critical for me
I think this could have definitely been easier. I could never have guessed what you wrote :-)

**Comment by jrichter-svmx** [comment]
Agree, when I was writing it, I noticed it is too complicated. We will try to make it easier :-)

**Comment by jrichter24** [comment]
Hey, please have a look at https://github.com/DNA-Evolutions/Java-TourOptimizer-Examples/blob/master/src/main/java/com/dna/jopt/touroptimizer/java/examples/advanced/readoutfullprogress/ReadOutFullProgressWithUtilExample.java
